apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-copilot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: incident-copilot
  template:
    metadata:
      labels:
        app: incident-copilot
    spec:
      containers:
        - name: incident-copilot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              value: "{{ .Values.env.OPENAI_API_KEY }}"